### PR TITLE
Add Shane Dell to people page

### PR DESCRIPTION
**Pull request by stevedlawrence**

### CODE REVIEW

**Comment by stevedlawrence** [comment]
@shanedell, please take a look at make sure this information is correct. This might also be a good first PR for you to merge to make sure all your Apache credentials and privileges are working.

**Review by Shanedell — APPROVED** [review]
+1

**Review by Shanedell — APPROVED** [review]
+1

**Comment by Shanedell** [comment]
@stevedlawrence Am I allowed to `rebase and merge` without a second approval? since this change just deals with add my information?

**Comment by stevedlawrence** [comment]
For the daffodil-site repo, yes. We really only require the two +1's on the daffodil code repo, and the new vscode repo. We have generally just trusted the committer about how many +1's they feel are needed (if any) for a change to the site.

**Pull request merged**
