### PR TITLE
Add release page for Apache Daffodil VS Code 1.2.0

### PR DESCRIPTION
**Pull request by Shanedell**

### CODE REVIEW

**Review by mbeckerle — APPROVED** [review]
+1

**Comment by Shanedell** [comment]
@mbeckerle If you don't mind taking another look at this, I just updated in tandem with closing of rc1 and releasing of rc2.

**Review by stevedlawrence — APPROVED** [review]
+1

**Review by mbeckerle — APPROVED** [review]
+1

**Pull request merged**
